# Generated by Django 2.2.13 on 2020-09-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smellfactory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcomment',
            old_name='listingid',
            new_name='forumid',
        ),
    ]
